### ISSUE TITLE
Assetlib requirements

### ISSUE THREAD

**Issue by akien-mga** [blurymind/1dollar_gesture_recogniser#1]
Sorry for the delay, just checking the assetlib moderation queue now (need to program email notifications when new edits are done :)).

The assetlib unzips the contents of your repo directly in the user's project, so you should provide the `addons/<youraddon>/` folder directly in this git repo, so that it's unzipped in the right location out of the box.

**Comment by blurymind** [comment]
Hi @akien-mga 
It's updated now :)
Hope that is ok. Would you like me to do the same for my other addon?

**Comment by akien-mga** [comment]
Yep, it's good.
Sure, if you want your addons to be usable out of the box they should all use this layout.

**Comment by blurymind** [comment]
Hi Remi, it is updated now :) hope you like it

**Comment by blurymind** [comment]
will get to it when i get home :)
